Repository andresfelipecg/Group-12-COMP367-DevOps-frontend, pull requests merged in 2023-04, with the labels that each got.

#3 Add changes to query.js to get a course by ID – front End
  src/queries.js
Labels: bug

#5 unwanted icon
  public/favicon.ico
Labels: not required

#9 Add new query by ID to App.js
  src/App.js
Labels: bug, enhancement

#10 deleted logo.svg file
  src/logo.svg
Labels: not required

#11 changed color
  src/App.css
Labels: enhancement
